[package]
name = "bench-de"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
ciborium = "0.2.2"
criterion = "0.5.1"
serde = { version = "1.0.217", features = ["derive"] }

[[bench]]
name = "cbor"
harness = false
